### ISSUE TITLE
Multi-metric packets

### ISSUE THREAD

**Issue by tmcw** [sivy/node-statsd#34]
It seems like it would be feasible to [send batched messages](https://github.com/etsy/statsd/blob/master/docs/metric_types.md#multi-metric-packets) through this api as well as one-metric-per udp-packet messages. Would this fit into the current plans?

**Comment by devdazed** [comment]
Interesting, I'm not sure how the API would look for this though, maybe something similar to redis, like:

``` js
client.multi(function(multi){
  multi.increment('foo.bar');
  multi.timing('response_time', 42);
});
```

ideas?

**Comment by tpiron** [comment]
There is actually a library where you can find some examples : https://github.com/msiebuhr/node-statsd-client/blob/master/lib/EphemeralSocket.js

They use :
- options.socketTimeout to send every X ms the buffer to statsd if it's not empty, otherwise they close the connection.
- options.maxBufferSize to bufferize all the values

**Comment by kadishmal** [comment]
I've reviewed the proposed code. Seems nice, except for one place where I've left a comment. What is the plan for merging this PR?

We're sending many metrics and would be nice to merge multiple metrics into one using this new `multi()` function.

**Comment by tmcw** [comment]
Closing as idle.
